In [1]:
import pandas as pd
import numpy as np
import os
import sys
import shutil
import time
from random import randint
import xlrd
import openpyxl

In [2]:
#cargamos datos de minderest
ruta = 'C:/Users/67075622/OneDrive - El Corte Inglés, S.A/Python/Pricing/'
archivo = 'Datos Minderest.xlsx'
df = pd.read_excel(ruta + archivo)

In [3]:
df

,Retailer,Country,SKU,Name,Brand,Category Level 1,Category Level 2,MPN,Min,Max,Avg,2021-10-04 00:00:00,2021-10-05 00:00:00,2021-10-06 00:00:00,2021-10-07 00:00:00,2021-10-08 00:00:00,2021-10-09 00:00:00,2021-10-10 00:00:00
0,elcorteingles_es,SPAIN,1015215003623,"Sobremesa Asus S300MA-710700006T, i7, 16GB, 51...",asus,Ord.per.hardwar,NaN,A39946666,"719,2",899,"821,94","719,2","719,2","719,2",899,899,899,899
1,elcorteingles_es,SPAIN,1015216118032,"""Monitor PC 61,2 cm (24,1"""") ASUS ProArt PA248...",asus,Ord.per.hardwar,Monitores,A39175207,259,259,259,NaN,NaN,259,NaN,NaN,NaN,NaN
2,amazon.es,SPAIN,1015215582865,"Portátil Gaming ASUS TUF A17 FA706QM-HX001, AM...",asus,Ord.per.hardwar,Portatiles pc,A40073835,"1469,65",1549,"1496,1",NaN,NaN,NaN,NaN,"1469,65","1469,65",1549
3,amazon.es,SPAIN,1015215579051,"Chromebook portátil Acer CB314-1H-C75Z, Intel ...",acer,Ord.per.hardwar,Portatiles pc,A38041598,"298,9","408,9","361,76","298,9","298,9","298,9","408,9","408,9","408,9","408,9"
4,elcorteingles_es,SPAIN,1028645002016,Joystick Thrustmaster T.16000M FCS Space Sim Duo,thrustmaster,Ac.inf.cons.sof,Mando para juegos,A24746269,129,129,129,129,129,129,129,129,129,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22182,fnac.es/marketplace,SPAIN,1028611111111,EXTRA,EXTRA,EXTRA,EXTRA,EXTRA,0,0,0,0,0,0,0,0,0,0
22183,carrefour-noalimentacion_es,SPAIN,1028611111111,EXTRA,EXTRA,EXTRA,EXTRA,EXTRA,0,0,0,0,0,0,0,0,0,0
22184,amazon.es,SPAIN,1028611111111,EXTRA,EXTRA,EXTRA,EXTRA,EXTRA,0,0,0,0,0,0,0,0,0,0
22185,samsung_es,SPAIN,1028611111111,EXTRA,EXTRA,EXTRA,EXTRA,EXTRA,0,0,0,0,0,0,0,0,0,0
22186,pccomponentes,SPAIN,1028611111111,EXTRA,EXTRA,EXTRA,EXTRA,EXTRA,0,0,0,0,0,0,0,0,0,0